website/models.py
# model bazy

website/__init__.py
from flask import Flask
import os

from website.blueprints.home import home_bp
from website.blueprints.map1 import map1_bp
from website.blueprints.map_Kasia import map_Kasia_bp
from website.blueprints.map_Tomek import map_Tomek_bp
from website.blueprints.map_Gabrysia import map_Gabrysia_bp
from website.blueprints.map_Marcysia import map_Marcysia_bp


def create_app():
    app = Flask(__name__)

    app.register_blueprint(home_bp)
    app.register_blueprint(map1_bp)
    app.register_blueprint(map_Kasia_bp)
    app.register_blueprint(map_Tomek_bp)
    app.register_blueprint(map_Gabrysia_bp)
    app.register_blueprint(map_Marcysia_bp)
    return app

website/blueprints/home.py
from flask import Blueprint, render_template

home_bp = Blueprint('home', __name__)


@home_bp.route('/')
def home():
    return render_template('home.html')

website/blueprints/map1.py
from flask import Blueprint, render_template

# map1_bp = Blueprint('map1', __name__)

# @map1_bp.route('/map1')
# def map1():
#     return render_template('map1.html')

# from flask import render_template
from website.maps.generate_map1 import generate_map1

map1_bp = Blueprint('map1', __name__)


@map1_bp.route('/map1')
def map1():
    graph = generate_map1()

    return render_template('map1.html', graph=graph)

website/blueprints/map_Gabrysia.py
from flask import Blueprint, render_template
from website.maps.generate_map_Gabrysia import generate_map_Gabrysia

map_Gabrysia_bp = Blueprint('map_Gabrysia', __name__)


@map_Gabrysia_bp.route('/map_Gabrysia')
def map_Gabrysia():
    graph = generate_map_Gabrysia()

    return render_template('map_Gabrysia.html', graph=graph)

website/blueprints/map_Kasia.py
from flask import Blueprint, render_template
from website.maps.generate_map_Kasia import generate_map_Kasia

map_Kasia_bp = Blueprint('map_Kasia', __name__)


@map_Kasia_bp.route('/map_Kasia')
def map_Kasia():
    graph = generate_map_Kasia()

    return render_template('map_Kasia.html', graph=graph)

website/blueprints/map_Marcysia.py
from flask import Blueprint, render_template
from website.maps.generate_map_Marcysia import generate_map_Marcysia

map_Marcysia_bp = Blueprint('map_Marcysia', __name__)


@map_Marcysia_bp.route('/map_Marcysia')
def map_Marcysia():
    graph = generate_map_Marcysia()

    return render_template('map_Marcysia.html', graph=graph)

website/blueprints/map_Tomek.py
from flask import Blueprint, render_template
from website.maps.generate_map_Tomek import generate_map_Tomek

map_Tomek_bp = Blueprint('map_Tomek', __name__)


@map_Tomek_bp.route('/map_Tomek')
def map_Tomek():
    graph = generate_map_Tomek()

    return render_template('map_Tomek.html', graph=graph)

website/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
<!--<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/home.css') }}"> z jakiegoś powowdu mi nie działa ~ Adam -->
    <link rel="stylesheet" type="text/css" href="../static/css/home.css">

    
</head>
</head>
<body>
    <div class="container">
        <div class="header-content">
            <h1 class="header-content__title">Wizualizacja danych geoprzestrzennych</h1>
        </div>
        <div class="menu_content">
            <div class="menu_item " data-index="0">
                <div class="menu_item--hidden">
                </div>
                <div class="menu_item--main gus_item">
                    <h2 class="menu_item__title">Dane GUS</h2>
                    <p class="menu_item__line"></p>
                </div>
            </div>
            <div class="menu_item " data-index="1">
                <div class="menu_item--hidden"></div>
                <div class="menu_item--main weather_item">
                    <h2 class="menu_item__title">Prognoza pogody</h2>
                    <p class="menu_item__line"></p>
                </div>
            </div>
            <div class="menu_item fire_item" data-index="2">
                <div class="menu_item--hidden"></div>
                <div class="menu_item--main">
                    <h2 class="menu_item__title">Choroba serca</h2>
                    <p class="menu_item__line"></p>
                </div>
            </div>
            <div class="menu_item czwarty_item" data-index="3">
                <div class="menu_item--hidden"></div>
                <div class="menu_item--main">
                    <h2 class="menu_item__title">Pożary w USA</h2>
                    <p class="menu_item__line"></p>
                </div>
            </div>
        </div>
        <div class="footer"></div>
    </div>

    
</body>
<script>
const imageDivs = document.querySelectorAll('.menu_item');
const imageDivsM = document.querySelectorAll('.menu_item--main');
console.log(imageDivsM)
const imageDivsH = document.querySelectorAll('.menu_item--hidden');
const lines = document.querySelectorAll('.menu_item__line');

const titles= document.querySelectorAll('.menu_item__title');

// imageDivsM[0].style.backgroundImage =  "url({{ url_for ('static', filename = 'images/menu_item_1/fire.jpg') }})"
imageDivsM[0].style.backgroundImage =  "url({{ url_for ('static', filename = 'images/menu_item_3/imageonline/00.jpg') }})"
imageDivsM[1].style.backgroundImage =  "url({{ url_for ('static', filename = 'images/menu_item_2/imageonline/10.jpg') }})"
imageDivsM[2].style.backgroundImage =  "url({{ url_for ('static', filename = 'images/menu_item_4/imageonline/30.jpg') }})"
imageDivsM[3].style.backgroundImage =  "url({{ url_for ('static', filename = 'images/menu_item_1/imageonline/20.jpg') }})"


imageDivs.forEach(imageDiv => {
    console.log('forech')
    imageDiv.addEventListener('mouseover', ()=>{
        lines.forEach(line => {
            line.style.display = 'block'
        })
        const index = imageDiv.getAttribute('data-index');
        if(index == 0){
            imageDivsH[1].style.left = '0'
            imageDivsH[2].style.left = '0'
            imageDivsH[3].style.left = '0'
            imageDivsH[0].style.backgroundImage =  "url({{ url_for ('static', filename = 'images/menu_item_3/imageonline/00.jpg') }})"
            imageDivsH[1].style.backgroundImage = "url({{ url_for ('static', filename = 'images/menu_item_3/imageonline/10.jpg') }})"
            imageDivsH[2].style.backgroundImage = "url({{ url_for ('static', filename = 'images/menu_item_3/imageonline/20.jpg') }})"
            imageDivsH[3].style.backgroundImage = "url({{ url_for ('static', filename = 'images/menu_item_3/imageonline/30.jpg') }})"
            titles[0].style.display = 'block'
            titles[1].style.display = 'none'
            titles[2].style.display = 'none'
            titles[3].style.display = 'none'
        }
        else if(index == 1){
            imageDivsH[0].style.backgroundImage =  "url({{ url_for ('static', filename = 'images/menu_item_2/imageonline/00.jpg') }})"
            imageDivsH[1].style.backgroundImage = "url({{ url_for ('static', filename = 'images/menu_item_2/imageonline/10.jpg') }})"
            imageDivsH[2].style.backgroundImage = "url({{ url_for ('static', filename = 'images/menu_item_2/imageonline/20.jpg') }})"
            imageDivsH[3].style.backgroundImage = "url({{ url_for ('static', filename = 'images/menu_item_2/imageonline/30.jpg') }})"
            titles[0].style.display = 'none'
            titles[1].style.display = 'block'
            titles[2].style.display = 'none'
            titles[3].style.display = 'none'
            imageDivsH[0].style.left = '0'
            imageDivsH[2].style.left = '0'
            imageDivsH[3].style.left = '0'
        }
        else if(index == 2){
            imageDivsH[0].style.backgroundImage =  "url({{ url_for ('static', filename = 'images/menu_item_4/imageonline/10.jpg') }})"
            imageDivsH[1].style.backgroundImage = "url({{ url_for ('static', filename = 'images/menu_item_4/imageonline/00.jpg') }})"
            imageDivsH[2].style.backgroundImage = "url({{ url_for ('static', filename = 'images/menu_item_4/imageonline/30.jpg') }})"
            imageDivsH[3].style.backgroundImage = "url({{ url_for ('static', filename = 'images/menu_item_4/imageonline/20.jpg') }})"
            titles[0].style.display = 'none'
            titles[1].style.display = 'none'
            titles[2].style.display = 'block'
            titles[3].style.display = 'none'
            imageDivsH[0].style.left = '0'
            imageDivsH[1].style.left = '0'
            imageDivsH[3].style.left = '0'
        }
        else if(index == 3){
            imageDivsH[0].style.backgroundImage =  "url({{ url_for ('static', filename = 'images/menu_item_1/imageonline/30.jpg') }})"
            imageDivsH[1].style.backgroundImage = "url({{ url_for ('static', filename = 'images/menu_item_1/imageonline/00.jpg') }})"
            imageDivsH[2].style.backgroundImage = "url({{ url_for ('static', filename = 'images/menu_item_1/imageonline/10.jpg') }})"
            imageDivsH[3].style.backgroundImage = "url({{ url_for ('static', filename = 'images/menu_item_1/imageonline/20.jpg') }})"
            titles[0].style.display = 'none'
            titles[1].style.display = 'none'
            titles[2].style.display = 'none'
            titles[3].style.display = 'block'
            imageDivsH[0].style.left = '0'
            imageDivsH[1].style.left = '0'
            imageDivsH[2].style.left = '0'
        }
})})

imageDivs.forEach(imageDiv => {
    imageDiv.addEventListener('mouseout', ()=>{
    imageDivsH.forEach(imageDivH =>{
        imageDivH.style.left = '-100%'
    })

    lines.forEach(line => {
            line.style.display = 'none'
        })
    titles[0].style.display = 'block'
    titles[1].style.display = 'block'
    titles[2].style.display = 'block'
    titles[3].style.display = 'block'
})})



imageDivs[0].addEventListener("click", function() {
        // Przenieś użytkownika na wskazaną stronę (np. 'map1')
        window.location.href = "{{ url_for('map_Marcysia.map_Marcysia') }}";
});

imageDivs[1].addEventListener("click", function() {
        // Przenieś użytkownika na wskazaną stronę (np. 'map1')
        window.location.href = "{{ url_for('map_Tomek.map_Tomek') }}";
});

imageDivs[2].addEventListener("click", function() {
        // Przenieś użytkownika na wskazaną stronę (np. 'map1')
        window.location.href = "{{ url_for('map_Gabrysia.map_Gabrysia') }}";
});

imageDivs[3].addEventListener("click", function() {
        // Przenieś użytkownika na wskazaną stronę (np. 'map1')
        window.location.href = "{{ url_for('map_Kasia.map_Kasia') }}";
});

</script>
</html>

website/templates/map1.html
<!DOCTYPE html>
<html>
<head>
    <title>Map Page</title>
</head>
<body>
    <h1>Map Page</h1>
    {{ graph|safe }}
</body>
</html>

website/templates/map_Gabrysia.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mapa - Gabrysia</title>
</head>
<body>
    <h1>Mapa - Gabrysia</h1>
    {{ graph|safe }}
</body>
</html>

website/templates/map_Kasia.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mapa - Kasia</title>
</head>
<body>
    <h1>Mapa - Kasia</h1>
    {{ graph|safe }}
</body>
</html>

website/templates/map_Marcysia.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mapa - Marcysia</title>
</head>
<body>
    <h1>Mapa - Marcysia</h1>
    {{ graph|safe }}
</body>
</html>

website/templates/map_Tomek.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mapa - Tomek</title>
</head>
<body>
    <h1>Mapa - Tomek</h1>
    {{ graph|safe }}
</body>
</html>